# Generated by Django 4.2.10 on 2024-03-04 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('socialapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicks',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks_user', to='users.user'),
        ),
        migrations.AddField(
            model_name='socialapps',
            name='user_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='socialapps_user', to='users.user'),
            preserve_default=False,
        ),
    ]
